In [ ]:
import numpy as np

In [6]:
#############################################################################################################
#  CREAR UN ARRAY DEL 0 AL 9
#############################################################################################################

a = np.arange(10)
a

array([4, 5, 6, 7, 8, 9])

In [8]:
#############################################################################################################
#  CREAR UN ARRAY 3x3
#############################################################################################################

a = np.full((3, 3), True, dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
#############################################################################################################
#  CONDICIONAR UN ARRAY
#############################################################################################################

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [11]:
#############################################################################################################
# REEMPLAZAR VALUES DE UN ARRAY QUE CUMPLAN UNA CONDICION
#############################################################################################################

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
#############################################################################################################
# REEMPLAZAR VALUES DE UN ARRAY QUE CUMPLAN UNA CONDICION SIN MODIFICAR EL ARRAY PRINCIPAL
#############################################################################################################

arr = np.arange(10)

arr_final = np.where(arr % 2 == 1, -1, arr)
arr_final


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])